application:
  subdomain: mrrss
  multi_instance: true
  upstreams:
    - location: /
      backend: http://mrrss-server:1234/
services:
  mrrss-server:
    # ghcr.io/wcy-dt/mrrss:1.3.23
    # upstream: ghcr.io/wcy-dt/mrrss:1.3.23
    image: registry.lazycat.cloud/czyt/wcy-dt/mrrss:7be77cd769990df1
    user: mrrss
    environment:
      - MRRSS_DEBUG=false
    binds:
      - /lzcapp/var/data:/app/data
    setup_script: |
      mkdir -p /app/data
      chown -R mrrss:mrrss /app/data
    healthcheck:
      test:
        - CMD-SHELL
        - wget --no-verbose --tries=1 --spider http://localhost:1234/api/version || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
